[supervisord]
nodaemon=true
logfile=/app/data/logs/supervisord.log
logfile_maxbytes=10MB

[program:xvfb]
command=Xvfb :99 -screen 0 1920x1080x24
autorestart=true

[program:x11vnc]
command=x11vnc -display :99 -forever -nopw -rfbport 5900
autorestart=true

[program:novnc]
command=websockify --web /usr/share/novnc 6080 localhost:5900
autorestart=true

[program:daemon]
command=yarn daemon
directory=/app
environment=DISPLAY=":99"
autorestart=true
stdout_logfile=/app/data/logs/daemon.stdout.log
stderr_logfile=/app/data/logs/daemon.stderr.log
stdout_logfile_maxbytes=10MB
stderr_logfile_maxbytes=10MB
